-- Gunakan file berikut agar tidak salah project:
-- PROJECT FOTO  -> 01_FIX_UPLOADER_PHOTO.sql
-- PROJECT VIDEO -> 02_FIX_UPLOADER_VIDEO.sql
--
-- Kedua file tersebut sudah termasuk:
-- uploader = bisa upload, tidak bisa delete
-- admin    = bisa upload + delete
-- visitor  = hanya lihat
