-- ============================================================
-- ADMIN PASSWORD SECURITY — NEW ROOM
-- Jalankan di Supabase SQL Editor.
-- ============================================================

-- Pastikan role hanya boleh bernilai admin/uploader/visitor.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('admin', 'uploader', 'visitor'));

-- Helper aman untuk pengecekan role dari sisi database.
-- Tidak mengekspos password atau service role key.
create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_current_user_admin() from public;
grant execute on function public.is_current_user_admin() to authenticated;

-- Audit perubahan password oleh admin.
create table if not exists public.admin_password_resets (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_password_resets enable row level security;

drop policy if exists "Admins can view password reset audit" on public.admin_password_resets;
create policy "Admins can view password reset audit"
on public.admin_password_resets
for select
to authenticated
using (public.is_current_user_admin());

-- Tidak ada policy INSERT untuk authenticated.
-- Edge Function yang memakai service role dapat menulis audit jika diperlukan.
-- Service role bypasses RLS.
